### PR TITLE
Move _reset() in constructor to below the definitions of action_space

### LINKED ISSUE #219: Invalid assert in box2d/lunar_lander.py
I'm trying to use LunarLander-v2, but I'm getting an immediate error upon instantiation:

```
>>> import gym
>>> ll = gym.make('LunarLander-v2')
[2016-06-19 04:35:14,379] Making new env: LunarLander-v2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/repo/openai/gym/gym/envs/registration.py", line 86, in make
    return spec.make()
  File "/repo/openai/gym/gym/envs/registration.py", line 62, in make
    env = cls(**self._kwargs)
  File "/repo/openai/gym/gym/envs/box2d/lunar_lander.py", line 89, in __init__
    self._reset()
  File "/repo/openai/gym/gym/envs/box2d/lunar_lander.py", line 205, in _reset
    return self._step(0)[0]
  File "/repo/openai/gym/gym/envs/box2d/lunar_lander.py", line 229, in _step
    assert self.action_space.contains(action), "%r (%s) invalid " % (action,type(action))
AttributeError: 'NoneType' object has no attribute 'contains'
>>> 
```
This seems to be caused by commit 8a545eeb5942801d94dbd36e7d8be4c696d4bdd7 by @jietang. 

Reverting to the original code solved the problem. It seems the tighter assertions did not consider that `_reset()` calls `_step` [with (0)](https://github.com/openai/gym/blob/master/gym/envs/box2d/lunar_lander.py#L205), so either _reset needs to be fixed, or the assertions changed.

### PR DESCRIPTION
**Pull request by harvitronix**
Fixes #219

### CODE REVIEW

**Comment by jonasschneider** [comment]
Thanks!
