### ISSUE TITLE
classical_control Rending is Incompatible with Pyglet 1.4.0

### ISSUE THREAD

**Issue by wphuhn** [openai/gym#1588]
When running `examples/agent/cem.py` using the latest version of pyglet (1.4.0, released 5 July 2019), the script terminates early with the following output:

```
$ python3 ./cem.py 
INFO: Making new env: CartPole-v0
INFO: Clearing 3 monitor files from previous run (because force=True was provided)
INFO: Starting new video recorder writing to /tmp/cem-agent-results/openaigym.video.0.21090.video000000.mp4
Traceback (most recent call last):
  File "./cem.py", line 83, in <module>
    cem(noisy_evaluation, np.zeros(env.observation_space.shape[0]+1), **params)):
  File "./cem.py", line 28, in cem
    ys = np.array([f(th) for th in ths])
  File "./cem.py", line 28, in <listcomp>
    ys = np.array([f(th) for th in ths])
  File "./cem.py", line 78, in noisy_evaluation
    rew, T = do_rollout(agent, env, num_steps)
  File "./cem.py", line 37, in do_rollout
    ob = env.reset()
  File "/home/will/opt/OpenAI_Gym/gym/wrappers/monitor.py", line 39, in reset
    self._after_reset(observation)
  File "/home/will/opt/OpenAI_Gym/gym/wrappers/monitor.py", line 188, in _after_reset
    self.reset_video_recorder()
  File "/home/will/opt/OpenAI_Gym/gym/wrappers/monitor.py", line 209, in reset_video_recorder
    self.video_recorder.capture_frame()
  File "/home/will/opt/OpenAI_Gym/gym/wrappers/monitoring/video_recorder.py", line 101, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/home/will/opt/OpenAI_Gym/gym/core.py", line 233, in render
    return self.env.render(mode, **kwargs)
  File "/home/will/opt/OpenAI_Gym/gym/envs/classic_control/cartpole.py", line 188, in render
    return self.viewer.render(return_rgb_array = mode=='rgb_array')
  File "/home/will/opt/OpenAI_Gym/gym/envs/classic_control/rendering.py", line 105, in render
    arr = np.frombuffer(image_data.data, dtype=np.uint8)
AttributeError: 'ImageData' object has no attribute 'data'
INFO: Finished writing results. You can upload them to the scoreboard via gym.upload('/tmp/cem-agent-results')
```

This change in pyglet's API was already noted by @johny-c in issue #1438 along with a solution, but at the time, they realized they were running a pre-release version of pyglet, so they closed the issue.  This API change appears to have survived into the release version of piglet.

I've verified that the fix by @johny-c also works with pyglet 1.4.0, but in the meanwhile, I was also able to verify that this problem could be punted down the road by downgrading pyglet to version 1.3.2, i.e.
```
pip3 uninstall pyglet
pip3 install --user pyglet==1.3.2
```
after which the in `examples/agent/cem.py` worked as expected.

**Comment by wphuhn** [comment]
It appears this affects not only example scripts, but the CI (see the CI log in pull request #1589 for commit 2d9c46d).

**Comment by wphuhn** [comment]
This has been fixed by mandating that Pyglet <= 1.3.2 be used (see comments in pull request #1589), so I'm closing this issue out.
