### ISSUE TITLE
env.render returns error: item 1 in _argtypes_ passes a union by value

### ISSUE THREAD

**Issue by julienroyd** [openai/gym#1785]
Hi,

I use Ubuntu 18.04. I can reproduce this error in a minimal example by creating a new conda environment and only `pip install gym`, so that the env only contains the following packages:

```
certifi==2019.11.28
cloudpickle==1.2.2
future==0.18.2
gym==0.15.4
numpy==1.18.1
opencv-python==4.1.2.30
pyglet==1.3.2
scipy==1.4.1
six==1.13.0
```

When I run the following code in that env:

```
import gym
env = gym.make('CartPole-v0')
env.reset()

for _ in range(1000):
    env.render()
    env.step(env.action_space.sample())
```

I get the following error:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1035, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jroy4/anaconda3/envs/irl/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/jroy4/anaconda3/envs/irl/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 221, in <module>
    from .xlib import XlibConfig as Config
  File "/home/jroy4/anaconda3/envs/irl/lib/python3.7/site-packages/pyglet/gl/xlib.py", line 12, in <module>
    from pyglet.canvas.xlib import XlibCanvas
  File "/home/jroy4/anaconda3/envs/irl/lib/python3.7/site-packages/pyglet/canvas/__init__.py", line 103, in <module>
    from pyglet.canvas.xlib import XlibDisplay as Display
  File "/home/jroy4/anaconda3/envs/irl/lib/python3.7/site-packages/pyglet/canvas/xlib.py", line 19, in <module>
    from . import xlib_vidmoderestore
  File "/home/jroy4/anaconda3/envs/irl/lib/python3.7/site-packages/pyglet/canvas/xlib_vidmoderestore.py", line 23, in <module>
    from pyglet.libs.x11 import xlib
  File "/home/jroy4/anaconda3/envs/irl/lib/python3.7/site-packages/pyglet/libs/x11/xlib.py", line 2928, in <module>
    XEHeadOfExtensionList.argtypes = [XEDataObject]
TypeError: item 1 in _argtypes_ passes a union by value, which is unsupported.
```

Any idea what is going on? Thanks!

**Edit: I use python=3.7.6**

**Comment by julienroyd** [comment]
It seems that the error only occurs with `python=3.7.6`

The code sample works fine with `python=3.7.4`

**Comment by 0dj0bz** [comment]
Based on similar issues found in Google searches, it seems that 3.7.6 "fixed" some bugs that has broken quite a few libraries.

**Comment by 0dj0bz** [comment]
I upgraded pyglet to 1.4.10 and this fixed my issue with `python=3.7.6`.

**Comment by christopherhesse** [comment]
Thanks @0dj0bz for the workaround.  https://github.com/openai/gym/pull/1771 should hopefully fix this

**Comment by HenryJia** [comment]
Using pyglet>=1.4 seems to instead give me

```
Traceback (most recent call last):
  File "ppo-lunarlandercontinuous.py", line 49, in <module>
    recorder.capture_frame()
  File "/usr/lib/python3.8/site-packages/gym/wrappers/monitoring/video_recorder.py", line 101, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/usr/lib/python3.8/site-packages/gym/core.py", line 235, in render
    return self.env.render(mode, **kwargs)
  File "/usr/lib/python3.8/site-packages/gym/envs/box2d/lunar_lander.py", line 354, in render
    return self.viewer.render(return_rgb_array = mode=='rgb_array')
  File "/usr/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 105, in render
    arr = np.frombuffer(image_data.data, dtype=np.uint8)
AttributeError: 'ImageData' object has no attribute 'data'
```

Although I am using python 3.8

**Comment by christopherhesse** [comment]
#1771  was merged, please file a new issue if you observe this with `gym>=0.15.6`
