### ISSUE TITLE
[Bug Report] AttributeError: 'VideoRecorder' object has no attribute 'enabled'

### ISSUE THREAD

**Issue by Touutae-lab** [openai/gym#3109]
```env = gym.make("BipedalWalker-v3", render_mode="rgb_array", hardcore=True)

observation, info = env.reset()

env = gym.wrappers.RecordVideo(
    env=env,
    video_folder="./video_test",
    name_prefix="",
)
for _ in range(5000):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)
    if terminated:
        observation, info = env.reset() 
```

it happened when you try to step

**Comment by Touutae-lab** [comment]
I have seen the work are currenly in progress so i edited some of your code and seem it still working in gym 0.26

**Comment by pseudo-rnd-thoughts** [comment]
I believe the issue is that you wrap the environment after calling `reset`.

You need to use
```python
env = gym.wrappers.RecordVideo(
    env=env,
    video_folder="./video_test",
    name_prefix="",
)
observation, info = env.reset()
```
