### ISSUE TITLE
[Bug Report] Breaking changes not mentioned in gym 0.24 release notes

### ISSUE THREAD

**Issue by araffin** [openai/gym#2848]
Using pretrained agent from the RL Zoo (checking )

**Describe the bug**
First issue is that `LunarLander` observation space was changed without any version bump, this leads to:
```
ValueError: Observation spaces do not match: Box([-inf -inf -inf -inf -inf -inf -inf -inf], [-inf -inf -inf -inf -inf -inf -inf -inf], (8,), float32) != Box([-1.5       -1.5       -5.        -5.        -3.1415927 -5.
 -0.        -0.       ], [1.5       1.5       5.        5.        3.1415927 5.        1.
 1.       ], (8,), float32)
```
when trying to load pretrained model.

And in fact now breaks one of the largest collection of pre-trained models (600+ agents): https://huggingface.co/spaces/chrisjay/Deep-Reinforcement-Learning-Leaderboard

but another error occured before that one:

```
lib/python3.7/site-packages/gym/spaces/box.py", line 224, in __repr__
    return f"Box({self.low_repr}, {self.high_repr}, {self.shape}, {self.dtype})"
AttributeError: 'Box' object has no attribute 'low_repr'

``` 

introduced in https://github.com/openai/gym/pull/2554, the issue is the same as in https://github.com/DLR-RM/stable-baselines3/issues/573, the new variable breaks unpickling of previous version of that space.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for spotting that. 
We will add to the release notes that the observation space of `LunarLander` and `BipedalWalker` has been updated to not use infinities in the observation space
For your second issue, PR will fix this bug. 
Not sure on the release timetable, maybe in a week or so, this PR will be on the stable branch for all critical bug fixes related to v0.24 if you want to test with that in the meantime.

**Comment by jkterry1** [comment]
Fixed
