### ISSUE TITLE
Error during Installation

### ISSUE THREAD

**Issue by cookees** [openai/gym#780]
Sorry I'm a bit new to Python and this. I am installing on a Windows computer with BASH. However, I get an error when I try to install using pip install -e .. Was wondering if anyone could help me out thanks.

`jeremy@LAPTOP-KKRM2MEQ:/mnt/c/Users/Jeremy/Desktop/gym$ pip install -e .
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/jeremy/documents/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/home/jeremy/documents/bin/pip", line 7, in <module>
    from pip import main
  File "/home/jeremy/documents/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/home/jeremy/documents/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 62, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/home/jeremy/documents/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
  File "/home/jeremy/documents/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/home/jeremy/documents/lib/python2.7/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/home/jeremy/documents/lib/python2.7/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/home/jeremy/documents/lib/python2.7/site-packages/urllib3/util/__init__.py", line 6, in <module>
    from .ssl_ import (
  File "/home/jeremy/documents/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 7, in <module>
    from hashlib import md5, sha1, sha256
ImportError: cannot import name md5`

**Comment by FirefoxMetzger** [comment]
You could provide us with more information on what system you, e.g. which Windows (presumable 10) version? Python version (presumable 2.7)? And other things that might seem related  / necessary to solve this issue.

Also try to reinstall hashlib (which is what is not working as expected) 

    pip uninstall hashlib
    pip install hashlib

and make sure you have openSSL installed on your system (how would depend on your specific machine)

**Comment by cookees** [comment]
Yep Windows 10, I'm actually using Python 3.6 now, but I was using Python 2.7 before. I have just uninstalled Python 2.7 completely. I've re-installed hashlib now. 

I've been testing some stuff out, and I think I can install with sudo -H pip install -e .. When I install it, I get this, which shows that everything is installed correctly. My Gym File is on my Desktop. 

`Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python2.7/dist-packages (from gym==0.9.3)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python2.7/dist-packages (from gym==0.9.3)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from gym==0.9.3)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from gym==0.9.3)
Installing collected packages: gym
  Found existing installation: gym 0.9.3
    Can't uninstall 'gym'. No files were found to uninstall.
  Running setup.py develop for gym
Successfully installed gym`

However, when I create a sample program (file on Desktop too), I get the issue that module Gym has no make. Sorry I'm really new to all this, I think it's calling the gym file from my Desktop. Do you know where I should go from here?

`================ RESTART: C:/Users/Jeremy/Desktop/gymtest.py ================
Traceback (most recent call last):
  File "C:/Users/Jeremy/Desktop/gymtest.py", line 2, in <module>
    env = gym.make('CartPole-v0')
AttributeError: module 'gym' has no attribute 'make'
>>> `

**Comment by cookees** [comment]
Yep Windows 10, I'm actually using Python 3.6 IDLE right now to compile and write Python code. I've been testing some stuff out, and I think I can install gym with sudo -H pip install -e .. When I installed it, I get the code below, which shows that everything is installed correctly. My gym file is on my Desktop. When I installed gym, it installed a folder called Python 2.7 along with it, in my usr/local/bin folder. 

Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python2.7/dist-packages (from gym==0.9.3) Requirement already satisfied: requests>=2.0 in /usr/local/lib/python2.7/dist-packages (from gym==0.9.3) Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from gym==0.9.3) Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from gym==0.9.3) Installing collected packages: gym Found existing installation: gym 0.9.3 Can't uninstall 'gym'. No files were found to uninstall. Running setup.py develop for gym Successfully installed gym

However, when I create a sample program (file on Desktop too), I get the issue that module Gym has no make. Sorry I'm really new to all this, I think it's calling the gym file from my Desktop. Do you know where I should go from here?

================ RESTART: C:/Users/Jeremy/Desktop/gymtest.py ================ Traceback (most recent call last): File "C:/Users/Jeremy/Desktop/gymtest.py", line 2, in <module> env = gym.make('CartPole-v0') AttributeError: module 'gym' has no attribute 'make'

**Comment by cookees** [comment]
Ok so I have managed to get it working on my virtual machine that runs Ubuntu. But I would prefer to run on Windows, since it is a lot faster and there is less lag.

**Comment by FirefoxMetzger** [comment]
That error is different from what you posted above =) also there are a bunch of things that seem mixed up.

First of, I am surprised that ´sudo -H pip install -e .´ works on your system. ´sudo´ is a Unix command and is typically not recognized on WinOS.

Your command line shows something like ´/mnt/c/User/...´ which again suggests a unix filesystem which mounted your windows c drive. Are you using cygwin or something similar to do this?

Next you seem to have both a python3 and python2 interpreter installed on your machine. This makes the command `pip install X` ambiguous, as it is not clear whether you want to install X for python2 or python3. In your case `pip` seems to default to python2.7 (hence the path reference, which again is a unix path). You should be using `pip2` for python2 or `pip3` for python3 (assuming there is only one of each version-majors installed on your system) to solve this ambiguity.

Next the error `ImportError: No module named gym` suggests that python is unable to find the module called gym. This is because it is neither in a sub-folder of your script's directory, nor in the python path. Adding it to your python-path should remidy this situation. (Node that this will only work with python2.7 as you haven't installed gym on python3)

**Comment by FirefoxMetzger** [comment]
Also, as a side note, gym is currently not supported in native Windows (check [Supported Systems](https://github.com/openai/gym/blob/master/README.rst#supported-systems) ) so you might very well find that it is very hard to make work.

Depending on your Windows version, you could use Docker via Hyper-V or VirtualBox, which allows you to still write your code on the Windows machine, but run it in a linuxVM. (That is how I am doing it on my Windows Desktop at the moment and I don't experience any performance problems)

**Comment by andychlee** [comment]
Installing using WSL should work. Double check to make sure that the python you're using actually has the module installed. You might need to also install vcXsrv or Xming as well.

Also, refer to #11. There are working Windows install instructions.
You can just simply `pip install gym` and should work right from command prompt.

**Comment by christopherhesse** [comment]
Closing in favor of https://github.com/openai/gym/issues/11
