### ISSUE TITLE
Installing everything error in macos

### ISSUE THREAD

**Issue by ghost** [openai/gym#1614]
when i install everything,the following will error occur:
.. code:: shell

Building wheel for box2d-py (setup.py) ... error
  ERROR: Complete output from command /anaconda2/envs/gymlab/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/0v/m2krff5x0y9_ygsf4ct4pvww0000gn/T/pip-install-Pv2tKa/box2d-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/0v/m2krff5x0y9_ygsf4ct4pvww0000gn/T/pip-wheel-GyjM36 --python-tag cp27:

i use macos mojave-10.14.5, conda-4.5.11,python-2.7

**Comment by pzhokhov** [comment]
could you post the rest of the output here please? Also, if you are using gym for box2d, atari or mujoco environments, I would recommend using python 3.5+

**Comment by AlbertTHuanG** [comment]
the rest of the output:
`Building wheel for box2d-py (setup.py) ... error
  ERROR: Complete output from command /anaconda2/envs/gymlab/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/0v/m2krff5x0y9_ygsf4ct4pvww0000gn/T/pip-install-T5iJc5/box2d-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/0v/m2krff5x0y9_ygsf4ct4pvww0000gn/T/pip-wheel-5_iUBg --python-tag cp27:
  ERROR: Using setuptools (version 41.0.1).
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-2.7
  creating build/lib.macosx-10.6-x86_64-2.7/Box2D
  copying library/Box2D/Box2D.py -> build/lib.macosx-10.6-x86_64-2.7/Box2D
  copying library/Box2D/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/Box2D
  creating build/lib.macosx-10.6-x86_64-2.7/Box2D/b2
  copying library/Box2D/b2/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/Box2D/b2
  running build_ext
  building 'Box2D._Box2D' extension
  swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
  swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library/Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
  Box2D/Common/b2Math.h:67: Warning 302: Identifier 'b2Vec2' redefined by %extend (ignored),
  Box2D/Box2D_math.i:47: Warning 302: %extend definition of 'b2Vec2'.
  Box2D/Common/b2Math.h:158: Warning 302: Identifier 'b2Vec3' redefined by %extend (ignored),
  Box2D/Box2D_math.i:168: Warning 302: %extend definition of 'b2Vec3'.
  Box2D/Common/b2Math.h:197: Warning 302: Identifier 'b2Mat22' redefined by %extend (ignored),
  Box2D/Box2D_math.i:301: Warning 302: %extend definition of 'b2Mat22'.
  Box2D/Common/b2Math.h:271: Warning 302: Identifier 'b2Mat33' redefined by %extend (ignored),
  Box2D/Box2D_math.i:372: Warning 302: %extend definition of 'b2Mat33'.
  Box2D/Collision/b2DynamicTree.h:44: Warning 312: Nested union not currently supported (ignored).
  Box2D/Common/b2Settings.h:144: Warning 506: Can't wrap varargs with keyword arguments enabled
  Box2D/Common/b2Math.h:91: Warning 509: Overloaded method b2Vec2::operator ()(int32) effectively ignored,
  Box2D/Common/b2Math.h:85: Warning 509: as it is shadowed by b2Vec2::operator ()(int32) const.
  creating build/temp.macosx-10.6-x86_64-2.7
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Dynamics
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Dynamics/Contacts
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Dynamics/Joints
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Common
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Collision
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Collision/Shapes
  gcc -fno-strict-aliasing -I/anaconda2/envs/gymlab/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/gymlab/include/python2.7 -c Box2D/Box2D_wrap.cpp -o build/temp.macosx-10.6-x86_64-2.7/Box2D/Box2D_wrap.o -I. -Wno-unused
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  Box2D/Box2D_wrap.cpp:2686:10: fatal error: 'string' file not found
  #include <string>
           ^~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for box2d-py
  Running setup.py clean for box2d-py`

I can use atari in python-2.7.
wait for your reply

**Comment by AlbertTHuanG** [comment]
the rest of the output

`Building wheel for box2d-py (setup.py) ... error
  ERROR: Complete output from command /anaconda2/envs/gymlab/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/0v/m2krff5x0y9_ygsf4ct4pvww0000gn/T/pip-install-T5iJc5/box2d-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/0v/m2krff5x0y9_ygsf4ct4pvww0000gn/T/pip-wheel-5_iUBg --python-tag cp27:
  ERROR: Using setuptools (version 41.0.1).
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-2.7
  creating build/lib.macosx-10.6-x86_64-2.7/Box2D
  copying library/Box2D/Box2D.py -> build/lib.macosx-10.6-x86_64-2.7/Box2D
  copying library/Box2D/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/Box2D
  creating build/lib.macosx-10.6-x86_64-2.7/Box2D/b2
  copying library/Box2D/b2/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/Box2D/b2
  running build_ext
  building 'Box2D._Box2D' extension
  swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
  swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library/Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
  Box2D/Common/b2Math.h:67: Warning 302: Identifier 'b2Vec2' redefined by %extend (ignored),
  Box2D/Box2D_math.i:47: Warning 302: %extend definition of 'b2Vec2'.
  Box2D/Common/b2Math.h:158: Warning 302: Identifier 'b2Vec3' redefined by %extend (ignored),
  Box2D/Box2D_math.i:168: Warning 302: %extend definition of 'b2Vec3'.
  Box2D/Common/b2Math.h:197: Warning 302: Identifier 'b2Mat22' redefined by %extend (ignored),
  Box2D/Box2D_math.i:301: Warning 302: %extend definition of 'b2Mat22'.
  Box2D/Common/b2Math.h:271: Warning 302: Identifier 'b2Mat33' redefined by %extend (ignored),
  Box2D/Box2D_math.i:372: Warning 302: %extend definition of 'b2Mat33'.
  Box2D/Collision/b2DynamicTree.h:44: Warning 312: Nested union not currently supported (ignored).
  Box2D/Common/b2Settings.h:144: Warning 506: Can't wrap varargs with keyword arguments enabled
  Box2D/Common/b2Math.h:91: Warning 509: Overloaded method b2Vec2::operator ()(int32) effectively ignored,
  Box2D/Common/b2Math.h:85: Warning 509: as it is shadowed by b2Vec2::operator ()(int32) const.
  creating build/temp.macosx-10.6-x86_64-2.7
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Dynamics
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Dynamics/Contacts
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Dynamics/Joints
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Common
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Collision
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Collision/Shapes
  gcc -fno-strict-aliasing -I/anaconda2/envs/gymlab/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/gymlab/include/python2.7 -c Box2D/Box2D_wrap.cpp -o build/temp.macosx-10.6-x86_64-2.7/Box2D/Box2D_wrap.o -I. -Wno-unused
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  Box2D/Box2D_wrap.cpp:2686:10: fatal error: 'string' file not found
  #include <string>
           ^~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for box2d-py
  Running setup.py clean for box2d-py`

I can use atari in python-2.7
wait for your reply

**Comment by AlbertTHuanG** [comment]
the rest of the output

'''
Building wheel for box2d-py (setup.py) ... error
  ERROR: Complete output from command /anaconda2/envs/gymlab/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/0v/m2krff5x0y9_ygsf4ct4pvww0000gn/T/pip-install-T5iJc5/box2d-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/0v/m2krff5x0y9_ygsf4ct4pvww0000gn/T/pip-wheel-5_iUBg --python-tag cp27:
  ERROR: Using setuptools (version 41.0.1).
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-2.7
  creating build/lib.macosx-10.6-x86_64-2.7/Box2D
  copying library/Box2D/Box2D.py -> build/lib.macosx-10.6-x86_64-2.7/Box2D
  copying library/Box2D/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/Box2D
  creating build/lib.macosx-10.6-x86_64-2.7/Box2D/b2
  copying library/Box2D/b2/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/Box2D/b2
  running build_ext
  building 'Box2D._Box2D' extension
  swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
  swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library/Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
  Box2D/Common/b2Math.h:67: Warning 302: Identifier 'b2Vec2' redefined by %extend (ignored),
  Box2D/Box2D_math.i:47: Warning 302: %extend definition of 'b2Vec2'.
  Box2D/Common/b2Math.h:158: Warning 302: Identifier 'b2Vec3' redefined by %extend (ignored),
  Box2D/Box2D_math.i:168: Warning 302: %extend definition of 'b2Vec3'.
  Box2D/Common/b2Math.h:197: Warning 302: Identifier 'b2Mat22' redefined by %extend (ignored),
  Box2D/Box2D_math.i:301: Warning 302: %extend definition of 'b2Mat22'.
  Box2D/Common/b2Math.h:271: Warning 302: Identifier 'b2Mat33' redefined by %extend (ignored),
  Box2D/Box2D_math.i:372: Warning 302: %extend definition of 'b2Mat33'.
  Box2D/Collision/b2DynamicTree.h:44: Warning 312: Nested union not currently supported (ignored).
  Box2D/Common/b2Settings.h:144: Warning 506: Can't wrap varargs with keyword arguments enabled
  Box2D/Common/b2Math.h:91: Warning 509: Overloaded method b2Vec2::operator ()(int32) effectively ignored,
  Box2D/Common/b2Math.h:85: Warning 509: as it is shadowed by b2Vec2::operator ()(int32) const.
  creating build/temp.macosx-10.6-x86_64-2.7
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Dynamics
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Dynamics/Contacts
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Dynamics/Joints
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Common
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Collision
  creating build/temp.macosx-10.6-x86_64-2.7/Box2D/Collision/Shapes
  gcc -fno-strict-aliasing -I/anaconda2/envs/gymlab/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/gymlab/include/python2.7 -c Box2D/Box2D_wrap.cpp -o build/temp.macosx-10.6-x86_64-2.7/Box2D/Box2D_wrap.o -I. -Wno-unused
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  Box2D/Box2D_wrap.cpp:2686:10: fatal error: 'string' file not found
  #include <string>
           ^~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for box2d-py
  Running setup.py clean for box2d-py
'''

I can use atari in python2.7
wait for your reply

**Comment by christopherhesse** [comment]
Is there a reason you are using python2.7?  Python 3.5+ have prebuilt binaries and would be unlikely to fail in this way.

**Comment by christopherhesse** [comment]
Based on some google searching you can also try `xcode-select --install` and see if it fixes your header issue.

**Comment by AlbertTHuanG** [comment]
> Based on some google searching you can also try `xcode-select --install` and see if it fixes your header issue.

Thanks for the advice, but it didn't work

**Comment by BolunDai0216** [comment]
Can you check what python you are using by running "which python" or "which python3", I have experienced issues when using anaconda's python if that makes sense. 

When switching to /usr/bin/python3 I noticed a lot of the issues would just magically go away.

**Comment by christopherhesse** [comment]
Does it work with python 3.5+?

**Comment by winstonmo9** [comment]
I just had the exact same problem....

**Comment by jkterry1** [comment]
I'm closing this due to inactivity
